services:
  # Backend API Service (Development)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: prompt-backend-dev
    ports:
      - "8000:8000"
    volumes:
      - ./vector_db_storage:/app/vector_db_storage
      - .:/app  # Mount source code for development
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
      - FASTAPI_ENV=development
    env_file:
      - .env
    networks:
      - prompt-network
    restart: unless-stopped
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  prompt-network:
    driver: bridge

volumes:
  vector_db_storage:
